# Generated by Django 2.2 on 2021-03-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210318_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='time',
        ),
    ]
